name: Build windows
on: [workflow_call]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: echo "build windows"

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - run: flutter --version
      - run: flutter build windows

      - name: Setup Wix Toolset
        run: |
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Create MSI
        run: |
          $ref = "${{ github.ref_name }}"
          $ver = $ref.Substring(1)
          make msi version=$ver
          mv build/windows/wix/installer.msi friendly-fire-desktop-${{ github.ref_name }}.windows-amd64.msi

      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: friendly-fire-desktop-${{ github.ref_name }}.windows-amd64.msi
