name: Build

on:
  push:
    tags:
      - asdv*.*.*

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - run: echo "tests are ok. wink wink"

  build-windows:
    needs: [ test ]
    uses: ./.github/workflows/build-windows.yaml

  build-web:
    needs: [ test ]
    uses: ./.github/workflows/build-web.yaml

  draft-release:
    name: Draft new release
    runs-on: ubuntu-latest
    needs: [ build-windows, build-web ]
    steps:
      - name: Is this release or prerelease
        id: version
        run: |
          if [[ ${{ github.ref_name }} == *-* ]]
          then echo "::set-output name=IS_PRERELEASE::true"
          else echo "::set-output name=IS_RELEASE::true"
          fi

      - name: Configure Github CLI
        run: |
          gh config set prompt disabled

      - name: Create new prerelease
        if: ${{ steps.version.outputs.IS_PRERELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create --draft --prerelease --title "Prerelease ${{ github.ref_name }}" ${{ github.ref_name }} --repo ${{ github.repository }}

      - name: Create new release
        if: ${{ steps.version.outputs.IS_RELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create --draft --title "Release ${{ github.ref_name }}" ${{ github.ref_name }} --repo ${{ github.repository }}

      - name: Download all artifacts
        uses: actions/download-artifact@v3
      
      - run: tree

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} **/*.* --repo ${{ github.repository }}
