name: Release

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release download ${{ github.event.release.tag_name }} --repo ${{ github.repository }}

      - run : ls -la

      - name: Upload to public bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: |
          aws s3 cp . s3://gamebay/releases/test/ \
            --recursive \
            --acl public-read \
            --endpoint https://fra1.digitaloceanspaces.com
